### ISSUE TITLE
2.2.99.0 Update Social Media

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/OhScrap#53]
# 2.2.99.0 Update Social Media

* [x] create/update
  * [x] Kerbal Space Program forum
    * [x] update original post
      * [x] title
      * [x] content
    * [x] create release post
  * [x] CurseForge
  * [x] Twitter
  * [x] SpaceDock
  * [x] Reddit post
  * [] Patreon post
  * [ ] promo vid (30 sec)
    * [ ] Youtube
    * [ ] Twitch

this file: CC BY-NC-ND 4.0 by zer0Kerbal

**Comment by johnnycocas** [comment]
Since this is still open, I'll take the opportunity to tell you that the forum link to ScrapYard is in fact linking itself (OhScrap forum page) :P

![image](https://user-images.githubusercontent.com/78932414/193698635-37a908df-e4af-4154-942b-19a79e900dca.png)

My guess is it should link to the [ScrapYard forum page](https://forum.kerbalspaceprogram.com/index.php?/topic/192456-*) instead.

**Comment by zer0Kerbal** [comment]
@johnnycocas thank you. Been (slowly) working on updating all the documentation for OhScrap!
